# Generated by Django 5.0.1 on 2024-01-28 08:09

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Category name')),
                ('slug', models.CharField(max_length=255, unique=True, verbose_name='Category Safe URL')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Feature Web ID')),
                ('feature', models.CharField(max_length=255, unique=True, verbose_name='Feature')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tag Name')),
                ('slug', models.CharField(max_length=100, unique=True, verbose_name='Tag Safe URL')),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Technology Name')),
                ('slug', models.CharField(max_length=100, unique=True, verbose_name='Technology Safe URL')),
                ('icon', models.ImageField(default='images/technologies.default.png', upload_to='images/technologies/', validators=[django.core.validators.FileExtensionValidator(['svg'])], verbose_name='Technology Logo')),
            ],
            options={
                'verbose_name': 'Technology',
                'verbose_name_plural': 'Technologies',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Project Name')),
                ('slug', models.CharField(max_length=255, unique=True, verbose_name='Project Safe URL')),
                ('excerpt', models.CharField(max_length=255, unique=True, verbose_name='Project Excerpt')),
                ('case_study', models.TextField(verbose_name='Project Description')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Project Live Link')),
                ('github', models.CharField(blank=True, max_length=255, null=True, verbose_name='Project Repo')),
                ('type', models.CharField(choices=[('Client', 'client'), ('Hubby', 'client'), ('Side', 'side')], max_length=100, verbose_name='Project Type')),
                ('status', models.CharField(choices=[('Completed', 'completed'), ('Incomplete', 'incomplete')], max_length=100, verbose_name='Project Completion Status')),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(unique=True, verbose_name='Project Display Priority')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(related_name='categories', to='projects.category')),
                ('features', models.ManyToManyField(related_name='features', to='projects.feature')),
                ('services', models.ManyToManyField(related_name='services', to='services.service')),
                ('tags', models.ManyToManyField(related_name='tags', to='projects.tag')),
                ('technologies', models.ManyToManyField(related_name='technologies', to='projects.technology')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Image Web ID')),
                ('alt', models.CharField(max_length=255, verbose_name='Project Image Alternative Text')),
                ('image', models.ImageField(default='images/portfolio/default.jpg', upload_to='images/portfolio/', verbose_name='Project Image')),
                ('is_feature', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.project')),
            ],
        ),
    ]
