# Generated by Django 5.0.1 on 2024-02-08 16:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_status_alter_project_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='icon',
            field=models.FileField(default='images/technologies/default.svg', upload_to='images/technologies/', validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpeg', 'jpg', 'webp'])], verbose_name='Technology Logo'),
        ),
    ]
