# Generated by Django 5.0.1 on 2024-01-28 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Process Name')),
                ('slug', models.CharField(max_length=255, unique=True, verbose_name='Process Safe URL')),
                ('desc', models.TextField(verbose_name='Process Description')),
                ('icon', models.ImageField(default='images/processes/default.png', upload_to='images/processes/', verbose_name='Process Image')),
                ('icon_alt', models.CharField(max_length=255, verbose_name='Process Icon Alternative Text')),
                ('priority', models.PositiveSmallIntegerField(unique=True, verbose_name='Process Display Order/priority')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Process',
                'verbose_name_plural': 'Processes',
            },
        ),
    ]
