# Generated by Django 5.0.1 on 2024-01-28 10:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.FileField(default='images/services/default.png', upload_to='images/services/', validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg', 'jpeg', 'webp'])], verbose_name='Service Image'),
        ),
    ]
