# Generated by Django 5.0.1 on 2024-01-28 10:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=150, verbose_name='Hero headline')),
                ('subheading', models.TextField(max_length=300, verbose_name='Hero subheading')),
                ('headshot', models.ImageField(upload_to='images/personal/', verbose_name='Hero Avatar')),
                ('profile_img', models.ImageField(upload_to='images/personal/', verbose_name='About Image Display')),
                ('bio', models.TextField(verbose_name='Professional Summary')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('address', models.CharField(max_length=100, verbose_name='Location')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Socials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Social Media Platform')),
                ('icon', models.FileField(default='images/icons/default.svg', upload_to='images/icons/', validators=[django.core.validators.FileExtensionValidator(['svg', 'png'])], verbose_name='Social Media Icon')),
                ('icon_dark', models.FileField(blank=True, null=True, upload_to='images/icons/', validators=[django.core.validators.FileExtensionValidator(['svg', 'png'])], verbose_name='Social Media Dark Icon')),
                ('link', models.URLField(max_length=255, verbose_name='Social Media Link')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='accounts.profile')),
            ],
        ),
    ]
