# Generated by Django 5.0.1 on 2024-01-29 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Socials',
            new_name='Social',
        ),
        migrations.RenameField(
            model_name='social',
            old_name='name',
            new_name='platform',
        ),
    ]
