# Generated by Django 5.0.1 on 2024-02-08 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_socials_social_rename_name_social_platform'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='social',
            name='link',
            field=models.URLField(max_length=255, unique=True, verbose_name='Social Media Link'),
        ),
        migrations.AlterField(
            model_name='social',
            name='platform',
            field=models.CharField(max_length=100, unique=True, verbose_name='Social Media Platform'),
        ),
        migrations.AlterField(
            model_name='social',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social', to='accounts.profile'),
        ),
    ]
