# Generated by Django 5.0.1 on 2024-01-28 08:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_id', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Testimonial Web URL')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Testimonee Name')),
                ('role', models.CharField(max_length=255, verbose_name="Testimonee's Role")),
                ('company', models.CharField(max_length=255, verbose_name="Testimonee's Company")),
                ('review', models.TextField(verbose_name="Testimonee's Review")),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='images/testimonees/', verbose_name="Testimonee's Avatar")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
            },
        ),
    ]
